### ISSUE TITLE
make dt_binding_check fails to run twice in a row.

### ISSUE THREAD

**Issue by agx** [robherring/dt-schema#11]
When i run

```
make -j4 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- dt_binding_check
```

on next-20190725 the first time it passes (after fixing up https://www.spinics.net/lists/devicetree/msg300336.html) but when run the same command a second time it fails like

```
$ make -j4 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- dt_binding_check
arch/arm64/Makefile:56: CROSS_COMPILE_COMPAT not defined or empty, the compat vDSO will not be built
make[1]: Circular Documentation/devicetree/bindings/arm/atmel-at91.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/spear.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/stm32/stm32.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/rockchip.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/primecell.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/cpus.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/moxart.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/calxeda.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/qcom.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/axxia.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/bitmain.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/xilinx.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/renesas.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/al,alpine.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/sti.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/pmu.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/vt8500.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/tegra.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/socionext/milbeaut.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/sunxi.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/altera.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/altera/socfpga-clk-manager.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/fsl.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/sirf.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/digicolor.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/intel-ixp4xx.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/mediatek.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/l2c2x0.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/ti/ti,davinci.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/ti/nspire.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/psci.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/zte.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/nxp/lpc32xx.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/amlogic.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/arm/rda.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/bus/allwinner,sun50i-a64-de2.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/bus/allwinner,sun8i-a23-rsb.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/clock/imx8mn-clock.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/clock/fixed-clock.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/clock/fixed-factor-clock.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/clock/allwinner,sun4i-a10-ccu.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/clock/milbeaut-clock.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/crypto/allwinner,sun4i-a10-crypto.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/display/bridge/imx-nwl-dsi.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/display/panel/ronbo,rb070d30.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/display/panel/raspberrypi,7inch-touchscreen.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/display/panel/mitsubishi,aa121td01.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
  CHKDT   Documentation/devicetree/bindings/display/bridge/imx-nwl-dsi.yaml
make[1]: Circular Documentation/devicetree/bindings/display/panel/innolux,ee101ia-01d.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/display/panel/mitsubishi,aa104xd12.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/display/panel/pda,91-00156-a0.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/display/panel/tfc,s9700rtwv43tr-01b.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/display/panel/sgd,gktw70sdae4se.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/display/panel/armadeus,st0700-adapt.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/display/panel/dlc,dlc0700yzg-1.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/display/panel/tpo,tpg110.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/display/panel/ampire,am-480272h3tmqw-t01h.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/display/panel/bananapi,s070wv20-ct16.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/display/panel/panel-common.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/display/panel/lvds.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/display/allwinner,sun6i-a31-mipi-dsi.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/display/simple-framebuffer.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/example-schema.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/firmware/intel,ixp4xx-network-processing-engine.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/gpio/pl061-gpio.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/i2c/marvell,mv64xxx-i2c.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/i2c/allwinner,sun6i-a31-p2wi.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/i2c/i2c-gpio.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/iio/proximity/devantech-srf04.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/iio/pressure/bmp085.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/iio/adc/adi,ad7124.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/iio/adc/adi,ad7780.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/iio/adc/avia-hx711.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/iio/chemical/sensirion,sps30.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/iio/light/isl29018.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/iio/light/tsl2583.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/iio/light/tsl2772.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/iio/frequency/adf4371.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/iio/accel/adi,adxl372.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/iio/accel/adi,adxl345.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/input/gpio-vibrator.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/input/allwinner,sun4i-a10-lradc-keys.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/interrupt-controller/intel,ixp4xx-interrupt.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/interrupt-controller/arm,gic-v3.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/interrupt-controller/arm,gic.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/leds/backlight/lm3630a-backlight.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/misc/intel,ixp4xx-queue-manager.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/mmc/mmc-controller.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/mmc/allwinner,sun4i-a10-mmc.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/mtd/nand-controller.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/mtd/allwinner,sun4i-a10-nand.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/net/allwinner,sun4i-a10-mdio.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/net/snps,dwmac.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/net/ethernet-phy.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/net/mdio.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/net/allwinner,sun4i-a10-emac.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/net/allwinner,sun7i-a20-gmac.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/net/allwinner,sun8i-a83t-emac.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/net/ethernet-controller.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/nvmem/nvmem.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/nvmem/nvmem-consumer.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/nvmem/allwinner,sun4i-a10-sid.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/phy/allwinner,sun6i-a31-mipi-dphy.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/pinctrl/st,stm32-pinctrl.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/pinctrl/aspeed,ast2500-pinctrl.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/pinctrl/aspeed,ast2400-pinctrl.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/pwm/allwinner,sun4i-a10-pwm.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/regulator/fixed-regulator.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/regulator/regulator.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/regulator/max8660.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/regulator/gpio-regulator.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/riscv/sifive.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/riscv/cpus.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/rtc/rtc.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/rtc/trivial-rtc.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/rtc/allwinner,sun4i-a10-rtc.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/rtc/allwinner,sun6i-a31-rtc.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/serial/pl011.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/serial/snps-dw-apb-uart.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/sound/allwinner,sun4i-a10-spdif.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/sound/allwinner,sun4i-a10-i2s.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/spi/spi-gpio.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/spi/spi-controller.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/spi/spi-pl022.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/spi/allwinner,sun6i-a31-spi.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/spi/allwinner,sun4i-a10-spi.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/timer/arm,global_timer.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/timer/arm,arch_timer.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/timer/intel,ixp4xx-timer.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/timer/arm,arch_timer_mmio.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/trivial-devices.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/usb/generic-ehci.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/usb/usb-hcd.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/usb/generic-ohci.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
make[1]: Circular Documentation/devicetree/bindings/vendor-prefixes.example.dt.yaml <- Documentation/devicetree/bindings/processed-schema.yaml dependency dropped.
  CHKDT   Documentation/devicetree/bindings/arm/atmel-at91.example.dt.yaml
  CHKDT   Documentation/devicetree/bindings/arm/spear.example.dt.yaml
  CHKDT   Documentation/devicetree/bindings/arm/stm32/stm32.example.dt.yaml
Traceback (most recent call last):
  File "/var/scratch/librem5/linux/dt-bindings/bin/dt-doc-validate", line 61, in <module>
    ret = check_doc(args.yamldt)
  File "/var/scratch/librem5/linux/dt-bindings/bin/dt-doc-validate", line 33, in check_doc
    for error in sorted(dtschema.DTValidator.iter_schema_errors(testtree), key=lambda e: e.linecol):
  File "/var/scratch/librem5/linux/dt-bindings/lib/python3.7/site-packages/dtschema/lib.py", line 560, in iter_schema_errors
    meta_schema = cls.resolver.resolve_from_url(schema['$schema'])
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/var/scratch/librem5/linux/dt-bindings/bin/dt-doc-validate", line 61, in <module>
    ret = check_doc(args.yamldt)
  File "/var/scratch/librem5/linux/dt-bindings/bin/dt-doc-validate", line 33, in check_doc
    for error in sorted(dtschema.DTValidator.iter_schema_errors(testtree), key=lambda e: e.linecol):
  File "/var/scratch/librem5/linux/dt-bindings/lib/python3.7/site-packages/dtschema/lib.py", line 560, in iter_schema_errors
    meta_schema = cls.resolver.resolve_from_url(schema['$schema'])
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/var/scratch/librem5/linux/dt-bindings/bin/dt-doc-validate", line 61, in <module>
    ret = check_doc(args.yamldt)
  File "/var/scratch/librem5/linux/dt-bindings/bin/dt-doc-validate", line 33, in check_doc
    for error in sorted(dtschema.DTValidator.iter_schema_errors(testtree), key=lambda e: e.linecol):
  File "/var/scratch/librem5/linux/dt-bindings/lib/python3.7/site-packages/dtschema/lib.py", line 560, in iter_schema_errors
    meta_schema = cls.resolver.resolve_from_url(schema['$schema'])
TypeError: list indices must be integers or slices, not str
make[1]: *** [Documentation/devicetree/bindings/Makefile:12: Documentation/devicetree/bindings/arm/atmel-at91.example.dt.example.dts] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Documentation/devicetree/bindings/Makefile:12: Documentation/devicetree/bindings/arm/spear.example.dt.example.dts] Error 1
make[1]: *** [Documentation/devicetree/bindings/Makefile:12: Documentation/devicetree/bindings/arm/stm32/stm32.example.dt.example.dts] Error 1
make: *** [Makefile:1278: dt_binding_check] Error 2
```

after a 

```
git clean -dfx
make -j4 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- <board>_defconfig
```

things pass again. The error message doesn't give me an idea what could be wrong so filing this issue.

**Comment by robherring** [comment]
Fixed in the kernel
